apiVersion: apps/v1
kind: Deployment
metadata:
   name: redis-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         app: redis
   minReadySeconds: 10
   template:
      metadata:
         labels:
            app: redis
      spec:
         containers:
         - name: redis
           image: redis:5.0-alpine
